language: go
go:
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - 1.8
  - 1.9
  - tip
before_install:
  - go get -v github.com/fzerorubigd/onion
  - go get -v github.com/smartystreets/goconvey
  - go get -v github.com/axw/gocov/gocov
  - go get -v github.com/mattn/goveralls
  - if ! go get code.google.com/p/go.tools/cmd/cover; then go get golang.org/x/tools/cmd/cover; fi
script:
  - goveralls -v -service travis-ci -repotoken $COVERALLS_TOKEN || go test -v
matrix:
  allow_failures:
  - go: 1.4
  - go: 1.5
  - go: 1.6
  - go: tip

